# Generated by Django 4.2.3 on 2023-08-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=3)),
                ('mail_id', models.CharField(max_length=30)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.position')),
            ],
        ),
    ]
